name: toggle_config
description: Lib para consulta de toggles de configurações.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  manga_easy_sdk:
    git:
      url: https://github.com/manga-easy/manga_easy_sdk.git
      ref: v1.3.0
  client_driver:
    git:
      url: https://github.com/manga-easy/manga_easy_client_driver.git
      ref: v1.1.2
  manga_easy_persistent_database_service:
    git:
      url: https://github.com/manga-easy/manga_easy_persistent_database_service.git
      ref: v1.2.1
  get_it: ^7.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
